# Generated by Django 2.1.5 on 2019-07-10 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resaurant',
            new_name='Restaurant',
        ),
    ]
